services:
  - type: web
    name: gitpulse-mcp-server
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: GITHUB_TOKEN
        sync: false  # This will be set in Render dashboard
