services:
  - type: web
    name: gitpulse-mcp-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node build/mcp-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MCP_TRANSPORT
        value: http
      - key: GITHUB_TOKEN
        sync: false  # This will be set in Render dashboard
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: gitpulse-disk
      size: "1GB"
    runtime: node20
