services:services:

  - type: web  - type: web

    name: gitpulse-mcp-server    name: gitpulse-mcp-server

    runtime: python    env: python

    buildCommand: pip install -r requirements.txt    region: oregon

    startCommand: python src/server.py    plan: free

    plan: free    buildCommand: pip install -r requirements.txt

    autoDeploy: false    startCommand: python src/server.py

    envVars:    envVars:

      - key: ENVIRONMENT      - key: ENVIRONMENT

        value: production        value: production

      - key: GITHUB_TOKEN      - key: GITHUB_TOKEN

        sync: false        sync: false  # This will be set in Render dashboard
